plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.13'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'org.example'
version = '0.0.1-SNAPSHOT'
description = 'QuickDelivery'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    // starer test 안에도 충분한 기능이 있기에 우선 주석처리
    //testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    //starter web - @RestController, RequestMapping, Get, Post 등 API관련 핵심 기능
    implementation 'org.springframework.boot:spring-boot-starter-web'
    //data JPA - @Entity, ID, JPA Repository, findBy 와 같은 DB와 Entity 관련 기능
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    //validation - 요청값 검증 @NotNull, @NotBlank
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    //Lombok - @Getter, @Setter, RequiredArgsConstructor와 같은 반복 코드 줄여주는 기능
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    //postgresql
    runtimeOnly 'org.postgresql:postgresql'
}

tasks.named('test') {
    useJUnitPlatform()
}
